server {
    listen 80;
    server_name gymaitrainerstaging.duckdns.org;

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name gymaitrainerstaging.duckdns.org;

    # Get SSL certificates from Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/gymaitrainerstaging.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gymaitrainerstaging.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Serve Frontend (React/Vue)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy for backend API
    location /api {
        proxy_pass http://gym-trainer-backend-staging:8080; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
