name: CI/CD Gym App - Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend (Staging)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gymapp-backend:staging

      - name: Build and push Frontend (Staging)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gymapp-frontend:staging

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check secret existence
        run: |
          echo "REDIS_PASSWORD length = ${#REDIS_PASSWORD}"
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      - name: Deploy to Staging Azure VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/azure_key
          chmod 600 ~/.ssh/azure_key

          scp -o StrictHostKeyChecking=no -i ~/.ssh/azure_key .github/workflows/deploy-staging.sh ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_SERVER_IP }}:~/deploy.sh
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/azure_key ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_SERVER_IP }} "
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"
            export ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"
            export MAIL_HOST="${{ secrets.MAIL_HOST }}"
            export MAIL_PORT="${{ secrets.MAIL_PORT }}"
            export MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
            chmod +x ~/deploy.sh
            ~/deploy.sh
          "