name: CI/CD Gym App Full Stack

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gymapp-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gymapp-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sync the docker-compose.yml file from GitHub to Azure VM
      - name: Copy docker-compose.yml to Azure
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/app"

      # Generate .env from ALL secrets and restart containers
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            mkdir -p ~/app
            cd ~/app
            
            # Writing ALL secrets to .env file on Azure
            cat <<EOF > .env
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            MAIL_PORT=${{ secrets.MAIL_PORT }}
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            EOF

            # clean old containers and orphans
            docker compose down --remove-orphans

            # pull latest images and restart containers
            docker compose pull
            docker compose up -d --force-recreate
            
            # clean old Docker image to free up space
            docker image prune -f

            # Health Check 
            echo "Waiting for backend to start..."
            for i in {1..10}; do
              if curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
                echo "Deployment Successful"
                docker ps
                exit 0
              fi
              echo "Waiting... ($i/10)"
              sleep 10
            done

            echo "Deployment Failed - Printing backend logs:"
            docker compose logs --tail 100 gym-trainer-backend
            exit 1